version: '3.7'

# The different services that make up our "network" of containers
services:
  products-postgres:
    image: postgres:latest
    container_name: products-postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - acme_network

  products:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - acme_network
    depends_on:
      - products-postgres


networks:
  acme_network:
